"""add foreign keys to Mission

Revision ID: 03e5cf712b50
Revises: e34c2dab4471
Create Date: 2024-06-11 15:09:08.982949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e5cf712b50'
down_revision = 'e34c2dab4471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scientist_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('planet_id')
        batch_op.drop_column('scientist_id')

    # ### end Alembic commands ###
